name: GHGEssentials
version: 1.0
author: [Jasperdoit, rens4000]
website: https://gewoonhdgaming.nl
main: nl.gewoonhdgaming.ess.Main
commands:
  chatadmin:
    description: Commando voor chat admin!
    aliases: [ca]
  teleport:
    description: Teleporteer naar mensen!
    aliases: [tp]
  adminmode:
    description: Schakel adminmode in/uit
    aliases: [am]