name: GHGEssentials
version: 1.0
author: [Jasperdoit, rens4000]
website: https://gewoonhdgaming.nl
main: nl.gewoonhdgaming.ess.Main
commands:
  chatadmin:
    description: Commando voor chat admin!
    usage: /chatadmin <subcommando> [argumenten]
  teleport:
    description: Teleporteer naar mensen!
    usage: /teleport <speler> [speler]